# Generated by Django 5.2.5 on 2025-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='movies/videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
